/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { RouterItem } from "./components/router/router.interface";
export namespace Components {
    interface AbgRouter {
        "home": RouterItem;
        "notFound": RouterItem;
        "routes": RouterItem[];
    }
}
export interface AbgRouterCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLAbgRouterElement;
}
declare global {
    interface HTMLAbgRouterElement extends Components.AbgRouter, HTMLStencilElement {
    }
    var HTMLAbgRouterElement: {
        prototype: HTMLAbgRouterElement;
        new (): HTMLAbgRouterElement;
    };
    interface HTMLElementTagNameMap {
        "abg-router": HTMLAbgRouterElement;
    }
}
declare namespace LocalJSX {
    interface AbgRouter {
        "home"?: RouterItem;
        "notFound"?: RouterItem;
        "onAbgRouter"?: (event: AbgRouterCustomEvent<any>) => void;
        "routes"?: RouterItem[];
    }
    interface IntrinsicElements {
        "abg-router": AbgRouter;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "abg-router": LocalJSX.AbgRouter & JSXBase.HTMLAttributes<HTMLAbgRouterElement>;
        }
    }
}
